import { createHash } from "node:crypto";
import type { AuditEventId, IsoTimestamp, TransactionId } from "./model.js";
import type { OrganizationId, ProjectId, EnvironmentId, TenantContext } from "./tenancy-auth.js";
import type { SqlExecutor } from "./transaction-engine.js";
import { canonicalJson } from "./idempotency.js";
import { RegistryError } from "./registry-errors.js";

export type AuditCategory="REQUEST"|"POLICY_DECISION"|"SOURCE_TRANSACTION"|"SOURCE_FINALITY"|"ATTESTATION"|"VALIDATOR_SIGNATURES"|"DESTINATION_TRANSACTION"|"DESTINATION_FINALITY"|"RECONCILIATION"|"ADMINISTRATOR_INTERVENTION"|"STATE_TRANSITION";
export interface AuditRecord{id:AuditEventId;organizationId:OrganizationId;projectId:ProjectId;environmentId:EnvironmentId;transactionId:TransactionId;operationId:string;sequence:number;category:AuditCategory;actor:string;action:string;payload:Readonly<Record<string,unknown>>;payloadHash:`sha256:${string}`;previousHash:`sha256:${string}`|"GENESIS";recordHash:`sha256:${string}`;occurredAt:IsoTimestamp}
export interface AppendAuditInput{id:AuditEventId;transactionId:TransactionId;operationId:string;category:AuditCategory;actor:string;action:string;payload:Readonly<Record<string,unknown>>;occurredAt:IsoTimestamp}
export interface AuditStore{append(input:Omit<AuditRecord,"sequence"|"previousHash"|"recordHash">):Promise<AuditRecord>;list(context:Pick<TenantContext,"organizationId"|"projectId"|"environmentId">,transactionId:TransactionId):Promise<readonly AuditRecord[]>}
export interface OperationReconstruction{transactionId:TransactionId;operationId:string;records:readonly AuditRecord[];actors:readonly string[];categories:readonly AuditCategory[];complete:boolean;missing:readonly AuditCategory[];chainVerified:true;startedAt:IsoTimestamp;lastActivityAt:IsoTimestamp}
const required:readonly AuditCategory[]=["REQUEST","POLICY_DECISION","SOURCE_TRANSACTION","SOURCE_FINALITY","ATTESTATION","VALIDATOR_SIGNATURES","DESTINATION_TRANSACTION","DESTINATION_FINALITY","RECONCILIATION"];
export class AuditService{constructor(readonly store:AuditStore){}async record(context:TenantContext,input:AppendAuditInput){validateInput(input);rejectSecrets(input.payload);const payloadHash=digest(canonicalJson(input.payload));return this.store.append({...input,organizationId:context.organizationId,projectId:context.projectId,environmentId:context.environmentId,payloadHash});}
 async reconstruct(context:TenantContext,transactionId:TransactionId):Promise<OperationReconstruction>{const records=[...await this.store.list(context,transactionId)].sort((a,b)=>a.sequence-b.sequence);if(!records.length)throw new RegistryError("NOT_FOUND",`audit history not found: ${transactionId}`);let previous:"GENESIS"|`sha256:${string}`="GENESIS";for(let i=0;i<records.length;i++){const record=records[i]!;if(record.sequence!==i||record.previousHash!==previous||record.payloadHash!==digest(canonicalJson(record.payload))||record.recordHash!==recordDigest(record))throw new RegistryError("CONFLICT",`audit chain verification failed at sequence ${record.sequence}`);previous=record.recordHash;}const categories=[...new Set(records.map(x=>x.category))],missing=required.filter(x=>!categories.includes(x));return{transactionId,operationId:records[0]!.operationId,records,actors:[...new Set(records.map(x=>x.actor))].sort(),categories,complete:missing.length===0,missing,chainVerified:true,startedAt:records[0]!.occurredAt,lastActivityAt:records.at(-1)!.occurredAt};}}
function validateInput(v:AppendAuditInput){if(!v.id.startsWith("IW:AUDIT:")||!v.transactionId.startsWith("IW:TRANSACTION:")||!v.operationId.trim()||!v.actor.trim()||!v.action.trim()||!Number.isFinite(Date.parse(v.occurredAt)))throw new RegistryError("INVALID_ARGUMENT","audit identity, actor, action, and timestamp are required");}
function rejectSecrets(value:unknown,path="payload"){if(Array.isArray(value)){value.forEach((v,i)=>rejectSecrets(v,`${path}[${i}]`));return;}if(value&&typeof value==="object"){for(const[k,v]of Object.entries(value)){if(/secret|password|private.?key|api.?key|authorization|bearer/i.test(k))throw new RegistryError("INVALID_ARGUMENT",`secret material is prohibited in audit payload: ${path}.${k}`);rejectSecrets(v,`${path}.${k}`);}}}
function digest(value:string):`sha256:${string}`{return`sha256:${createHash("sha256").update(value).digest("hex")}`;}function recordDigest(r:Omit<AuditRecord,"recordHash">|AuditRecord):`sha256:${string}`{const{recordHash:_recordHash,...value}=r as AuditRecord;return digest(canonicalJson(value));}
export class InMemoryAuditStore implements AuditStore{records:AuditRecord[]=[];async append(input:Omit<AuditRecord,"sequence"|"previousHash"|"recordHash">){if(this.records.some(x=>x.id===input.id))throw new RegistryError("ALREADY_EXISTS","audit record is immutable");const chain=this.records.filter(x=>x.organizationId===input.organizationId&&x.projectId===input.projectId&&x.environmentId===input.environmentId&&x.transactionId===input.transactionId).sort((a,b)=>a.sequence-b.sequence),sequence=chain.length,previousHash:AuditRecord["previousHash"]=chain.at(-1)?.recordHash??"GENESIS";const draft:Omit<AuditRecord,"recordHash">={...structuredClone(input),sequence,previousHash};const record:AuditRecord={...draft,recordHash:recordDigest(draft)};this.records.push(record);return structuredClone(record);}async list(c:Pick<TenantContext,"organizationId"|"projectId"|"environmentId">,id:TransactionId){return this.records.filter(x=>x.organizationId===c.organizationId&&x.projectId===c.projectId&&x.environmentId===c.environmentId&&x.transactionId===id).map(x=>structuredClone(x));}}
type Row={record:AuditRecord};export class PostgresAuditStore implements AuditStore{constructor(readonly db:SqlExecutor){}async append(input:Omit<AuditRecord,"sequence"|"previousHash"|"recordHash">){return this.db.transaction(async client=>{await client.query("SELECT pg_advisory_xact_lock(hashtext($1))",[`${input.organizationId}|${input.projectId}|${input.environmentId}|${input.transactionId}`]);const x=await client.query<Row>("SELECT record FROM audit_records WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND transaction_id=$4 ORDER BY sequence DESC LIMIT 1",[input.organizationId,input.projectId,input.environmentId,input.transactionId]);const last=x.rows[0]?.record,sequence=(last?.sequence??-1)+1,previousHash:AuditRecord["previousHash"]=last?.recordHash??"GENESIS",draft:Omit<AuditRecord,"recordHash">={...input,sequence,previousHash},record:AuditRecord={...draft,recordHash:recordDigest(draft)};const inserted=await client.query("INSERT INTO audit_records(id,organization_id,project_id,environment_id,transaction_id,sequence,category,record_hash,record) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb) ON CONFLICT DO NOTHING",[record.id,record.organizationId,record.projectId,record.environmentId,record.transactionId,record.sequence,record.category,record.recordHash,JSON.stringify(record)]);if(inserted.rowCount!==1)throw new RegistryError("CONFLICT","audit sequence or ID already exists");return record;});}async list(c:Pick<TenantContext,"organizationId"|"projectId"|"environmentId">,id:TransactionId){const x=await this.db.query<Row>("SELECT record FROM audit_records WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 AND transaction_id=$4 ORDER BY sequence",[c.organizationId,c.projectId,c.environmentId,id]);return x.rows.map(r=>r.record);}}
