import assert from"node:assert/strict";import test from"node:test";import{AuditService,InMemoryAuditStore}from"./audit-service.js";import type{AuditCategory}from"./audit-service.js";import type{TenantContext}from"./tenancy-auth.js";
const context:TenantContext={organizationId:"IW:ORGANIZATION:one",projectId:"IW:PROJECT:one",environmentId:"IW:ENVIRONMENT:prod",credentialId:"IW:CREDENTIAL:auditor",subjectId:"operator",scopes:["transactions:read"],authenticationMethod:"API_KEY"},transactionId="IW:TRANSACTION:one" as const,operationId="IW:BRIDGE:one";
const categories:AuditCategory[]=["REQUEST","POLICY_DECISION","SOURCE_TRANSACTION","SOURCE_FINALITY","ATTESTATION","VALIDATOR_SIGNATURES","DESTINATION_TRANSACTION","DESTINATION_FINALITY","RECONCILIATION"];
async function complete(){const store=new InMemoryAuditStore(),service=new AuditService(store);for(const[index,category]of categories.entries())await service.record(context,{id:`IW:AUDIT:${index}`,transactionId,operationId,category,actor:index===0?"api-user":"coordinator",action:category.toLowerCase(),payload:{reference:`evidence-${index}`,policyVersion:"1"},occurredAt:new Date(Date.parse("2026-08-13T12:00:00Z")+index*1000).toISOString()});return{store,service};}
test("one transaction ID reconstructs the complete cross-network operation",async()=>{const v=await complete(),result=await v.service.reconstruct(context,transactionId);assert.equal(result.complete,true);assert.equal(result.chainVerified,true);assert.deepEqual(result.missing,[]);assert.equal(result.records.length,9);assert.deepEqual(result.records.map(x=>x.sequence),[0,1,2,3,4,5,6,7,8]);assert.deepEqual(result.actors,["api-user","coordinator"]);});
test("partial reconstruction explicitly reports missing evidence",async()=>{const store=new InMemoryAuditStore(),service=new AuditService(store);await service.record(context,{id:"IW:AUDIT:request",transactionId,operationId,category:"REQUEST",actor:"user",action:"created",payload:{requestId:"r"},occurredAt:"2026-08-13T12:00:00Z"});const result=await service.reconstruct(context,transactionId);assert.equal(result.complete,false);assert.equal(result.missing.includes("RECONCILIATION"),true);});
test("tampering with payload, linkage, or record hash is detected",async()=>{const v=await complete();v.store.records[2]={...v.store.records[2]!,payload:{reference:"tampered"}};await assert.rejects(v.service.reconstruct(context,transactionId),/chain verification failed/);});
test("tenant isolation prevents another organization from discovering history",async()=>{const v=await complete(),other={...context,organizationId:"IW:ORGANIZATION:other" as const};await assert.rejects(v.service.reconstruct(other,transactionId),/not found/);});
test("duplicate IDs are immutable and secret material is rejected",async()=>{const store=new InMemoryAuditStore(),service=new AuditService(store),input={id:"IW:AUDIT:one" as const,transactionId,operationId,category:"REQUEST" as const,actor:"user",action:"created",payload:{safe:"value"},occurredAt:"2026-08-13T12:00:00Z"};await service.record(context,input);await assert.rejects(service.record(context,input),/immutable/);await assert.rejects(service.record(context,{...input,id:"IW:AUDIT:secret",payload:{authorization:"Bearer secret"}}),/secret material/);});
test("administrator intervention is preserved without hiding original evidence",async()=>{const v=await complete();await v.service.record(context,{id:"IW:AUDIT:admin",transactionId,operationId,category:"ADMINISTRATOR_INTERVENTION",actor:"admin:alice",action:"manual_review_resolved",payload:{ticket:"INC-42",resolution:"resume"},occurredAt:"2026-08-13T12:10:00Z"});const result=await v.service.reconstruct(context,transactionId);assert.equal(result.categories.includes("ADMINISTRATOR_INTERVENTION"),true);assert.equal(result.records[0]?.category,"REQUEST");});
