import type { AssetId, IsoTimestamp, NetworkId } from "./model.js";
import type { EnvironmentId, OrganizationId, ProjectId } from "./tenancy-auth.js";
import type { SqlExecutor } from "./transaction-engine.js";
import { RegistryError } from "./registry-errors.js";

export type EmergencyControlId = `IW:EMERGENCY_CONTROL:${string}`;
export type EmergencyControlKind = "ASSET" | "SOURCE_NETWORK" | "DESTINATION_NETWORK" | "BRIDGE_DIRECTION" | "MINT" | "RELEASE" | "SETTLEMENT";
export type EmergencyRole = "EMERGENCY_OPERATOR" | "EMERGENCY_ADMIN";
export interface EmergencySelector { assetId?: AssetId; sourceNetworkId?: NetworkId; destinationNetworkId?: NetworkId }
export interface EmergencyControl { id: EmergencyControlId; organizationId: OrganizationId; projectId: ProjectId; environmentId: EnvironmentId; kind: EmergencyControlKind; selector: EmergencySelector; status: "ACTIVE" | "LIFTED"; reason: string; activatedBy: string; activatedAt: IsoTimestamp; liftedBy?: string; liftedAt?: IsoTimestamp }
export interface EmergencyPrincipal { subjectId: string; roles: readonly EmergencyRole[]; organizationId: OrganizationId; projectId: ProjectId; environmentId: EnvironmentId }
export interface EmergencyOperation extends EmergencySelector { action: "MINT" | "RELEASE" | "SETTLEMENT" }
export interface EmergencyControlStore { create(control: EmergencyControl): Promise<EmergencyControl>; update(control: EmergencyControl): Promise<EmergencyControl>; list(scope: Pick<EmergencyPrincipal,"organizationId"|"projectId"|"environmentId">): Promise<readonly EmergencyControl[]> }
export interface EmergencyAuditSink { record(event: { controlId: EmergencyControlId; actor: string; action: "ACTIVATED"|"LIFTED"; kind: EmergencyControlKind; selector: EmergencySelector; reason: string; occurredAt: IsoTimestamp }): Promise<void> }

export class EmergencyControlService {
  constructor(readonly store:EmergencyControlStore,readonly audit:EmergencyAuditSink,readonly now:()=>Date=()=>new Date()){}
  async activate(principal:EmergencyPrincipal,input:{id:EmergencyControlId;kind:EmergencyControlKind;selector:EmergencySelector;reason:string}){
    requireRole(principal,"EMERGENCY_OPERATOR");validate(input);const control:EmergencyControl={...input,organizationId:principal.organizationId,projectId:principal.projectId,environmentId:principal.environmentId,status:"ACTIVE",activatedBy:principal.subjectId,activatedAt:this.now().toISOString()};const stored=await this.store.create(control);await this.audit.record({controlId:stored.id,actor:principal.subjectId,action:"ACTIVATED",kind:stored.kind,selector:stored.selector,reason:stored.reason,occurredAt:stored.activatedAt});return stored;
  }
  async lift(principal:EmergencyPrincipal,id:EmergencyControlId,reason:string){requireRole(principal,"EMERGENCY_ADMIN");if(!reason.trim())throw new RegistryError("INVALID_ARGUMENT","lift reason is required");const current=(await this.store.list(principal)).find(x=>x.id===id);if(!current)throw new RegistryError("NOT_FOUND",`emergency control not found: ${id}`);if(current.status==="LIFTED")return current;const liftedAt=this.now().toISOString(),updated:EmergencyControl={...current,status:"LIFTED",liftedBy:principal.subjectId,liftedAt};const stored=await this.store.update(updated);await this.audit.record({controlId:id,actor:principal.subjectId,action:"LIFTED",kind:stored.kind,selector:stored.selector,reason,occurredAt:liftedAt});return stored;}
  async status(principal:EmergencyPrincipal){return this.store.list(principal);}
  async assertAllowed(principal:EmergencyPrincipal,operation:EmergencyOperation){const controls=(await this.store.list(principal)).filter(x=>x.status==="ACTIVE"&&matches(x,operation));if(controls.length)throw new RegistryError("CONFLICT",`operation paused by emergency control: ${controls.map(x=>x.id).join(",")}`);}
}
function requireRole(p:EmergencyPrincipal,role:EmergencyRole){if(!p.roles.includes(role))throw new RegistryError("CONFLICT",`missing required emergency role: ${role}`);}
function validate(v:{id:EmergencyControlId;kind:EmergencyControlKind;selector:EmergencySelector;reason:string}){if(!v.id.startsWith("IW:EMERGENCY_CONTROL:")||!v.reason.trim())throw new RegistryError("INVALID_ARGUMENT","control ID and reason are required");const s=v.selector;if(v.kind==="ASSET"&&!s.assetId||v.kind==="SOURCE_NETWORK"&&!s.sourceNetworkId||v.kind==="DESTINATION_NETWORK"&&!s.destinationNetworkId||v.kind==="BRIDGE_DIRECTION"&&(!s.sourceNetworkId||!s.destinationNetworkId))throw new RegistryError("INVALID_ARGUMENT",`selector is incomplete for ${v.kind}`);}
function matches(c:EmergencyControl,o:EmergencyOperation){const s=c.selector;if(s.assetId&&s.assetId!==o.assetId||s.sourceNetworkId&&s.sourceNetworkId!==o.sourceNetworkId||s.destinationNetworkId&&s.destinationNetworkId!==o.destinationNetworkId)return false;return c.kind==="ASSET"||c.kind==="SOURCE_NETWORK"||c.kind==="DESTINATION_NETWORK"||c.kind==="BRIDGE_DIRECTION"||c.kind===o.action;}

export class InMemoryEmergencyControlStore implements EmergencyControlStore{controls=new Map<EmergencyControlId,EmergencyControl>();async create(c:EmergencyControl){if(this.controls.has(c.id))throw new RegistryError("ALREADY_EXISTS","emergency control is immutable");this.controls.set(c.id,structuredClone(c));return structuredClone(c);}async update(c:EmergencyControl){const old=this.controls.get(c.id);if(!old||old.status!=="ACTIVE"||c.status!=="LIFTED")throw new RegistryError("CONFLICT","invalid emergency control update");this.controls.set(c.id,structuredClone(c));return structuredClone(c);}async list(s:Pick<EmergencyPrincipal,"organizationId"|"projectId"|"environmentId">){return[...this.controls.values()].filter(x=>x.organizationId===s.organizationId&&x.projectId===s.projectId&&x.environmentId===s.environmentId).map(x=>structuredClone(x));}}
type Row={record:EmergencyControl};export class PostgresEmergencyControlStore implements EmergencyControlStore{constructor(readonly db:SqlExecutor){}async create(c:EmergencyControl){const r=await this.db.query("INSERT INTO emergency_controls(id,organization_id,project_id,environment_id,status,record) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT DO NOTHING",[c.id,c.organizationId,c.projectId,c.environmentId,c.status,JSON.stringify(c)]);if(r.rowCount!==1)throw new RegistryError("ALREADY_EXISTS","emergency control already exists");return c;}async update(c:EmergencyControl){const r=await this.db.query("UPDATE emergency_controls SET status='LIFTED',record=$2::jsonb WHERE id=$1 AND status='ACTIVE'",[c.id,JSON.stringify(c)]);if(r.rowCount!==1)throw new RegistryError("CONFLICT","emergency control is not active");return c;}async list(s:Pick<EmergencyPrincipal,"organizationId"|"projectId"|"environmentId">){const r=await this.db.query<Row>("SELECT record FROM emergency_controls WHERE organization_id=$1 AND project_id=$2 AND environment_id=$3 ORDER BY created_at,id",[s.organizationId,s.projectId,s.environmentId]);return r.rows.map(x=>x.record);}}
