import assert from"node:assert/strict";import test from"node:test";import{HsmSigner,InMemorySigningStore,LocalDevelopmentSigner,MpcSigner,SigningCoordinator,signingPayloadDigest}from"./key-management.js";import type{TenantContext}from"./tenancy-auth.js";
const context:TenantContext={organizationId:"IW:ORGANIZATION:one",projectId:"IW:PROJECT:one",environmentId:"IW:ENVIRONMENT:prod",credentialId:"IW:CREDENTIAL:admin",subjectId:"admin",scopes:["policies:admin"],authenticationMethod:"API_KEY"};const policy={version:"1",environmentId:context.environmentId,allowedPurposes:["ATTESTATION","VALIDATOR_ROTATION"] as const,allowedAlgorithms:["ECDSA_SHA256"],allowedKeyPrefixes:["hsm://","mpc://"],privilegedPurposes:["VALIDATOR_ROTATION"] as const,requiredApprovals:2,maxValiditySeconds:300};
function request(purpose:"ATTESTATION"|"VALIDATOR_ROTATION"="ATTESTATION"){return{id:`IW:SIGNING_REQUEST:${purpose}` as const,purpose,operationId:"IW:BRIDGE:one",keyReference:"hsm://cluster/key-1",algorithm:"ECDSA_SHA256",payloadDigest:signingPayloadDigest(new TextEncoder().encode("payload")),policyVersion:"1",createdAt:"2026-08-13T12:00:00Z",expiresAt:"2026-08-13T12:05:00Z"};}
function fixture(purpose:"ATTESTATION"|"VALIDATOR_ROTATION"="ATTESTATION"){const calls:any[]=[];const signer=new HsmSigner({sign:async x=>{calls.push(x);return{signature:"hsm-signature",signedAt:"2026-08-13T12:02:00Z"}}});const store=new InMemorySigningStore(),coordinator=new SigningCoordinator(store,policy,signer,()=>new Date("2026-08-13T12:01:00Z"));return{calls,store,coordinator,input:request(purpose)};}
test("coordinator sends only opaque reference and digest to HSM",async()=>{const v=fixture();await v.coordinator.submit(context,v.input);const result=await v.coordinator.execute(context,v.input.id);assert.equal(result.provider,"HSM");assert.deepEqual(Object.keys(v.calls[0]).sort(),["algorithm","digest","keyReference","requestId"]);assert.equal(JSON.stringify(v.calls).includes("payload"),false);});
test("MPC signer uses the same custody-neutral contract",async()=>{const calls:any[]=[];const signer=new MpcSigner({sign:async x=>{calls.push(x);return{signature:"mpc-signature",signedAt:"2026-08-13T12:02:00Z"}}});const input={...request(),keyReference:"mpc://quorum/key-1"};const store=new InMemorySigningStore(),c=new SigningCoordinator(store,{...policy,allowedKeyPrefixes:["mpc://"]},signer,()=>new Date("2026-08-13T12:01:00Z"));await c.submit(context,input);assert.equal((await c.execute(context,input.id)).provider,"MPC");assert.equal(calls.length,1);});
test("privileged signing requires distinct exact-request approvals",async()=>{const v=fixture("VALIDATOR_ROTATION");await v.coordinator.submit(context,v.input);await assert.rejects(v.coordinator.execute(context,v.input.id),/2 distinct approvals/);await v.coordinator.approve(context,v.input.id,"alice","APPROVE");await assert.rejects(v.coordinator.approve(context,v.input.id,"alice","APPROVE"),/already decided/);await v.coordinator.approve(context,v.input.id,"bob","APPROVE");assert.equal((await v.coordinator.execute(context,v.input.id)).signature,"hsm-signature");});
test("rejecting approval, tenant mismatch, policy mismatch, and expiry fail closed",async()=>{const v=fixture("VALIDATOR_ROTATION");await v.coordinator.submit(context,v.input);await v.coordinator.approve(context,v.input.id,"alice","REJECT");await assert.rejects(v.coordinator.execute(context,v.input.id),/rejecting approval/);const w=fixture();await w.coordinator.submit(context,w.input);await assert.rejects(w.coordinator.execute({...context,projectId:"IW:PROJECT:other"},w.input.id),/another tenant/);await assert.rejects(w.coordinator.submit(context,{...w.input,id:"IW:SIGNING_REQUEST:bad",algorithm:"UNKNOWN"}),/does not authorize/);});
test("local signer is development-only and never accepts production reference",async()=>{assert.throws(()=>new LocalDevelopmentSigner("local-dev://one",new Uint8Array(31),"DEVELOPMENT"),/256-bit/);const signer=new LocalDevelopmentSigner("local-dev://one",new Uint8Array(32).fill(7),"DEVELOPMENT");const dev={...context,environmentId:"IW:ENVIRONMENT:dev" as const};const input={...request(),id:"IW:SIGNING_REQUEST:dev" as const,keyReference:"local-dev://one"};const store=new InMemorySigningStore(),c=new SigningCoordinator(store,{...policy,environmentId:dev.environmentId,allowedKeyPrefixes:["local-dev://"]},signer,()=>new Date("2026-08-13T12:01:00Z"));await c.submit(dev,input);assert.equal((await c.execute(dev,input.id)).provider,"LOCAL_DEVELOPMENT");});
test("signature results are replay-safe and signer is invoked once",async()=>{const v=fixture();await v.coordinator.submit(context,v.input);await v.coordinator.execute(context,v.input.id);await v.coordinator.execute(context,v.input.id);assert.equal(v.calls.length,1);});
