import { createHash, createHmac } from "node:crypto";
import type { IsoTimestamp } from "./model.js";
import type { EnvironmentId, OrganizationId, ProjectId, TenantContext } from "./tenancy-auth.js";
import type { SqlExecutor } from "./transaction-engine.js";
import { canonicalJson, requestFingerprint } from "./idempotency.js";
import { RegistryError } from "./registry-errors.js";

export type SigningPurpose="ATTESTATION"|"NETWORK_TRANSACTION"|"VALIDATOR_ROTATION"|"PAUSE_PROTOCOL"|"POLICY_ADMIN";
export interface SigningRequest{id:`IW:SIGNING_REQUEST:${string}`;organizationId:OrganizationId;projectId:ProjectId;environmentId:EnvironmentId;purpose:SigningPurpose;operationId:string;keyReference:string;algorithm:string;payloadDigest:`sha256:${string}`;policyVersion:string;createdAt:IsoTimestamp;expiresAt:IsoTimestamp}
export interface SigningApproval{id:`IW:SIGNING_APPROVAL:${string}`;requestId:SigningRequest["id"];requestDigest:string;approverId:string;decision:"APPROVE"|"REJECT";occurredAt:IsoTimestamp}
export interface SigningPolicy{version:string;environmentId:EnvironmentId;allowedPurposes:readonly SigningPurpose[];allowedAlgorithms:readonly string[];allowedKeyPrefixes:readonly string[];privilegedPurposes:readonly SigningPurpose[];requiredApprovals:number;maxValiditySeconds:number}
export interface SignatureResult{requestId:SigningRequest["id"];keyReference:string;algorithm:string;signature:string;signedAt:IsoTimestamp;provider:"LOCAL_DEVELOPMENT"|"HSM"|"MPC"}
export interface Signer{readonly provider:SignatureResult["provider"];sign(request:SigningRequest):Promise<SignatureResult>}
export interface ExternalSigningProvider{sign(input:{keyReference:string;algorithm:string;digest:string;requestId:string}):Promise<{signature:string;signedAt:IsoTimestamp}>}
export class HsmSigner implements Signer{readonly provider="HSM" as const;constructor(readonly client:ExternalSigningProvider){}async sign(r:SigningRequest){assertExternalReference(r.keyReference,"hsm://");const x=await this.client.sign({keyReference:r.keyReference,algorithm:r.algorithm,digest:r.payloadDigest,requestId:r.id});return{requestId:r.id,keyReference:r.keyReference,algorithm:r.algorithm,signature:x.signature,signedAt:x.signedAt,provider:this.provider};}}
export class MpcSigner implements Signer{readonly provider="MPC" as const;constructor(readonly client:ExternalSigningProvider){}async sign(r:SigningRequest){assertExternalReference(r.keyReference,"mpc://");const x=await this.client.sign({keyReference:r.keyReference,algorithm:r.algorithm,digest:r.payloadDigest,requestId:r.id});return{requestId:r.id,keyReference:r.keyReference,algorithm:r.algorithm,signature:x.signature,signedAt:x.signedAt,provider:this.provider};}}
export class LocalDevelopmentSigner implements Signer{readonly provider="LOCAL_DEVELOPMENT" as const;constructor(readonly keyReference:string,readonly secret:Uint8Array,readonly environment:"DEVELOPMENT"){if(environment!=="DEVELOPMENT"||!keyReference.startsWith("local-dev://")||secret.length<32)throw new RegistryError("INVALID_ARGUMENT","local signer is restricted to development with an in-memory 256-bit key");}async sign(r:SigningRequest){if(r.keyReference!==this.keyReference||r.environmentId.includes(":prod"))throw new RegistryError("CONFLICT","local development signer cannot sign this request");return{requestId:r.id,keyReference:r.keyReference,algorithm:r.algorithm,signature:createHmac("sha256",this.secret).update(r.payloadDigest).digest("hex"),signedAt:new Date().toISOString(),provider:this.provider};}}
export interface SigningStore{create(request:SigningRequest):Promise<SigningRequest>;get(id:SigningRequest["id"]):Promise<SigningRequest|undefined>;addApproval(value:SigningApproval):Promise<void>;approvals(id:SigningRequest["id"]):Promise<readonly SigningApproval[]>;saveResult(value:SignatureResult):Promise<SignatureResult>;getResult(id:SigningRequest["id"]):Promise<SignatureResult|undefined>}
export class SigningCoordinator{constructor(readonly store:SigningStore,readonly policy:SigningPolicy,readonly signer:Signer,readonly now:()=>Date=()=>new Date()){}
 async submit(context:TenantContext,input:Omit<SigningRequest,"organizationId"|"projectId"|"environmentId">){const request:SigningRequest={...input,organizationId:context.organizationId,projectId:context.projectId,environmentId:context.environmentId};this.validate(request);return this.store.create(request);}
 async approve(context:TenantContext,requestId:SigningRequest["id"],approverId:string,decision:SigningApproval["decision"]){if(!context.scopes.includes("policies:admin"))throw new RegistryError("CONFLICT","administrative approval scope is required");const request=await this.required(requestId);const value:SigningApproval={id:`IW:SIGNING_APPROVAL:${requestId}:${approverId}`,requestId,requestDigest:requestFingerprint(request),approverId,decision,occurredAt:this.now().toISOString()};await this.store.addApproval(value);return value;}
 async execute(context:TenantContext,id:SigningRequest["id"]){const existing=await this.store.getResult(id);if(existing)return existing;const request=await this.required(id);this.validate(request);if(request.organizationId!==context.organizationId||request.projectId!==context.projectId||request.environmentId!==context.environmentId)throw new RegistryError("CONFLICT","signing request belongs to another tenant");const approvals=await this.store.approvals(id),digest=requestFingerprint(request);if(approvals.some(x=>x.requestDigest!==digest||x.decision==="REJECT"))throw new RegistryError("CONFLICT","signing request has invalid or rejecting approval");const required=this.policy.privilegedPurposes.includes(request.purpose)?this.policy.requiredApprovals:0;if(new Set(approvals.filter(x=>x.decision==="APPROVE").map(x=>x.approverId)).size<required)throw new RegistryError("CONFLICT",`signing request requires ${required} distinct approvals`);const result=await this.signer.sign(request);if(!result.signature.trim()||!Number.isFinite(Date.parse(result.signedAt)))throw new RegistryError("INVALID_ARGUMENT","signer returned invalid evidence");return this.store.saveResult(result);}
 async required(id:SigningRequest["id"]){const r=await this.store.get(id);if(!r)throw new RegistryError("NOT_FOUND",`signing request not found: ${id}`);return r;}
 validate(r:SigningRequest){if(r.environmentId!==this.policy.environmentId||r.policyVersion!==this.policy.version||!this.policy.allowedPurposes.includes(r.purpose)||!this.policy.allowedAlgorithms.includes(r.algorithm)||!this.policy.allowedKeyPrefixes.some(x=>r.keyReference.startsWith(x)))throw new RegistryError("CONFLICT","signing policy does not authorize request");const created=Date.parse(r.createdAt),expires=Date.parse(r.expiresAt);if(!r.id.startsWith("IW:SIGNING_REQUEST:")||!r.operationId.trim()||!/^sha256:[0-9a-f]{64}$/.test(r.payloadDigest)||!Number.isFinite(created)||!Number.isFinite(expires)||created>=expires||(expires-created)/1000>this.policy.maxValiditySeconds||this.now().getTime()>=expires)throw new RegistryError("INVALID_ARGUMENT","signing request is invalid or expired");}}
function assertExternalReference(value:string,prefix:string){if(!value.startsWith(prefix)||value.includes("private")||value.includes("secret"))throw new RegistryError("INVALID_ARGUMENT",`signer requires an opaque ${prefix} key reference`);}
export function signingPayloadDigest(bytes:Uint8Array):`sha256:${string}`{return`sha256:${createHash("sha256").update(bytes).digest("hex")}`;}
export class InMemorySigningStore implements SigningStore{requests=new Map<string,SigningRequest>();approvalLog:SigningApproval[]=[];results=new Map<string,SignatureResult>();async create(r:SigningRequest){if(this.requests.has(r.id))throw new RegistryError("ALREADY_EXISTS","signing request is immutable");this.requests.set(r.id,structuredClone(r));return structuredClone(r);}async get(id:SigningRequest["id"]){return this.requests.get(id);}async addApproval(v:SigningApproval){if(this.approvalLog.some(x=>x.requestId===v.requestId&&x.approverId===v.approverId))throw new RegistryError("CONFLICT","approver already decided");this.approvalLog.push(structuredClone(v));}async approvals(id:SigningRequest["id"]){return this.approvalLog.filter(x=>x.requestId===id);}async saveResult(v:SignatureResult){if(this.results.has(v.requestId))throw new RegistryError("CONFLICT","signature result is immutable");this.results.set(v.requestId,structuredClone(v));return v;}async getResult(id:SigningRequest["id"]){return this.results.get(id);}}
type Row<T>={record:T};export class PostgresSigningStore implements SigningStore{constructor(readonly db:SqlExecutor){}async create(r:SigningRequest){const x=await this.db.query("INSERT INTO signing_requests(id,organization_id,project_id,environment_id,record) VALUES($1,$2,$3,$4,$5::jsonb) ON CONFLICT(id) DO NOTHING",[r.id,r.organizationId,r.projectId,r.environmentId,JSON.stringify(r)]);if(x.rowCount!==1)throw new RegistryError("ALREADY_EXISTS","signing request is immutable");return r;}async get(id:SigningRequest["id"]){const x=await this.db.query<Row<SigningRequest>>("SELECT record FROM signing_requests WHERE id=$1",[id]);return x.rows[0]?.record;}async addApproval(v:SigningApproval){const x=await this.db.query("INSERT INTO signing_approvals(id,request_id,approver_id,record) VALUES($1,$2,$3,$4::jsonb) ON CONFLICT(request_id,approver_id) DO NOTHING",[v.id,v.requestId,v.approverId,JSON.stringify(v)]);if(x.rowCount!==1)throw new RegistryError("CONFLICT","approver already decided");}async approvals(id:SigningRequest["id"]){const x=await this.db.query<Row<SigningApproval>>("SELECT record FROM signing_approvals WHERE request_id=$1 ORDER BY id",[id]);return x.rows.map(r=>r.record);}async saveResult(v:SignatureResult){const x=await this.db.query("INSERT INTO signing_results(request_id,record) VALUES($1,$2::jsonb) ON CONFLICT(request_id) DO NOTHING",[v.requestId,JSON.stringify(v)]);if(x.rowCount!==1)throw new RegistryError("CONFLICT","signature result is immutable");return v;}async getResult(id:SigningRequest["id"]){const x=await this.db.query<Row<SignatureResult>>("SELECT record FROM signing_results WHERE request_id=$1",[id]);return x.rows[0]?.record;}}
