import { metrics, SpanStatusCode, trace, type Attributes, type Counter, type Histogram, type Meter, type Span, type Tracer, type UpDownCounter } from "@opentelemetry/api";

export type TraceStage="api"|"coordinator"|"adapter"|"network_request"|"validator"|"aggregator"|"destination"|"reconciler";
export const METRIC_NAMES={transactionLatency:"interweave.transaction.duration",bridgeLatency:"interweave.bridge.duration",attestationLatency:"interweave.attestation.duration",sourceFinalityLatency:"interweave.finality.source.duration",destinationFinalityLatency:"interweave.finality.destination.duration",validatorUptime:"interweave.validator.checks",validatorDisagreement:"interweave.validator.disagreements",eventIngestionLag:"interweave.event.ingestion.lag",reconciliationMismatch:"interweave.reconciliation.mismatches",rpcErrors:"interweave.rpc.errors",cantonApiErrors:"interweave.canton.api.errors",stuckTransactions:"interweave.transactions.stuck"}as const;
const allowedAttributes=new Set(["service.name","deployment.environment","network.type","operation.type","operation.state","outcome","error.type","validator.status","finality.kind","event.type","rpc.method","canton.operation","trace.stage"]);
export function safeAttributes(input:Readonly<Record<string,string|number|boolean|undefined>>):Attributes{const output:Record<string,string|number|boolean>={};for(const[key,value]of Object.entries(input))if(value!==undefined&&allowedAttributes.has(key))output[key]=value;return output;}
export interface ObservationContext{networkType?:string;operationType?:string;operationState?:string;outcome?:string;errorType?:string}
export class InterWeaveObservability{
 readonly tracer:Tracer;readonly meter:Meter;readonly histograms:Record<"transaction"|"bridge"|"attestation"|"sourceFinality"|"destinationFinality"|"ingestionLag",Histogram>;readonly counters:Record<"validatorChecks"|"validatorDisagreement"|"reconciliationMismatch"|"rpcErrors"|"cantonErrors",Counter>;readonly stuck:UpDownCounter;readonly #stuckIds=new Set<string>();
 constructor(input:{tracer?:Tracer;meter?:Meter;instrumentationVersion?:string}={}){const version=input.instrumentationVersion??"0.1.0";this.tracer=input.tracer??trace.getTracer("@interweave/core",version);this.meter=input.meter??metrics.getMeter("@interweave/core",version);this.histograms={transaction:this.meter.createHistogram(METRIC_NAMES.transactionLatency,{unit:"s"}),bridge:this.meter.createHistogram(METRIC_NAMES.bridgeLatency,{unit:"s"}),attestation:this.meter.createHistogram(METRIC_NAMES.attestationLatency,{unit:"s"}),sourceFinality:this.meter.createHistogram(METRIC_NAMES.sourceFinalityLatency,{unit:"s"}),destinationFinality:this.meter.createHistogram(METRIC_NAMES.destinationFinalityLatency,{unit:"s"}),ingestionLag:this.meter.createHistogram(METRIC_NAMES.eventIngestionLag,{unit:"s"})};this.counters={validatorChecks:this.meter.createCounter(METRIC_NAMES.validatorUptime),validatorDisagreement:this.meter.createCounter(METRIC_NAMES.validatorDisagreement),reconciliationMismatch:this.meter.createCounter(METRIC_NAMES.reconciliationMismatch),rpcErrors:this.meter.createCounter(METRIC_NAMES.rpcErrors),cantonErrors:this.meter.createCounter(METRIC_NAMES.cantonApiErrors)};this.stuck=this.meter.createUpDownCounter(METRIC_NAMES.stuckTransactions);}
 async span<T>(stage:TraceStage,name:string,attributes:Readonly<Record<string,string|number|boolean|undefined>>,work:(span:Span)=>Promise<T>):Promise<T>{return this.tracer.startActiveSpan(`interweave.${stage}.${name}`,{attributes:safeAttributes({...attributes,"trace.stage":stage})},async span=>{try{const result=await work(span);span.setStatus({code:SpanStatusCode.OK});return result;}catch(error){span.setStatus({code:SpanStatusCode.ERROR,message:error instanceof Error?error.name:"UnknownError"});span.setAttribute("error.type",error instanceof Error?error.name:"UnknownError");throw error;}finally{span.end();}});}
 recordDuration(kind:keyof InterWeaveObservability["histograms"],seconds:number,context:ObservationContext={}){if(!Number.isFinite(seconds)||seconds<0)return;this.histograms[kind].record(seconds,safeAttributes(attrs(context)));}
 validatorCheck(healthy:boolean,networkType:string){this.counters.validatorChecks.add(1,safeAttributes({"validator.status":healthy?"healthy":"unhealthy","network.type":networkType}));}
 validatorDisagreement(networkType:string){this.counters.validatorDisagreement.add(1,safeAttributes({"network.type":networkType}));} reconciliationMismatch(operationType:string){this.counters.reconciliationMismatch.add(1,safeAttributes({"operation.type":operationType}));}
 rpcError(networkType:string,method:string,errorType:string){this.counters.rpcErrors.add(1,safeAttributes({"network.type":networkType,"rpc.method":method,"error.type":errorType}));} cantonError(operation:string,errorType:string){this.counters.cantonErrors.add(1,safeAttributes({"network.type":"CANTON","canton.operation":operation,"error.type":errorType}));}
 markStuck(operationId:string,context:ObservationContext={}){if(this.#stuckIds.has(operationId))return;this.#stuckIds.add(operationId);this.stuck.add(1,safeAttributes(attrs(context)));} clearStuck(operationId:string,context:ObservationContext={}){if(!this.#stuckIds.delete(operationId))return;this.stuck.add(-1,safeAttributes(attrs(context)));}
}
function attrs(c:ObservationContext){return{"network.type":c.networkType,"operation.type":c.operationType,"operation.state":c.operationState,outcome:c.outcome,"error.type":c.errorType};}
export async function tracedApi<T>(o:InterWeaveObservability,operation:string,work:(span:Span)=>Promise<T>){return o.span("api",operation,{"operation.type":operation},work);}export async function tracedCoordinator<T>(o:InterWeaveObservability,operation:string,work:(span:Span)=>Promise<T>){return o.span("coordinator",operation,{"operation.type":operation},work);}export async function tracedAdapter<T>(o:InterWeaveObservability,networkType:string,operation:string,work:(span:Span)=>Promise<T>){return o.span("adapter",operation,{"network.type":networkType,"operation.type":operation},work);}export async function tracedNetworkRequest<T>(o:InterWeaveObservability,networkType:string,method:string,work:(span:Span)=>Promise<T>){return o.span("network_request",method,{"network.type":networkType,"rpc.method":method},work);}export async function tracedValidator<T>(o:InterWeaveObservability,networkType:string,work:(span:Span)=>Promise<T>){return o.span("validator","verify",{"network.type":networkType},work);}export async function tracedAggregator<T>(o:InterWeaveObservability,work:(span:Span)=>Promise<T>){return o.span("aggregator","threshold",{},work);}export async function tracedDestination<T>(o:InterWeaveObservability,networkType:string,work:(span:Span)=>Promise<T>){return o.span("destination","execute",{"network.type":networkType},work);}export async function tracedReconciler<T>(o:InterWeaveObservability,work:(span:Span)=>Promise<T>){return o.span("reconciler","compare",{},work);}
