import assert from "node:assert/strict";import test from "node:test";import {AuthenticationService,InMemoryTenantRegistry,TenantAuthorizedBackend,TenantNetworkAuthorizer,hashApiKey,issueApiKey}from"./tenancy-auth.js";
const ids={o:"IW:ORGANIZATION:one" as const,p:"IW:PROJECT:one" as const,e:"IW:ENVIRONMENT:prod" as const,c:"IW:CREDENTIAL:one" as const,s:"IW:SERVICE_ACCOUNT:api" as const};
function fixture(){const r=new InMemoryTenantRegistry(),createdAt="2026-08-13T12:00:00.000Z";r.organizations.set(ids.o,{id:ids.o,name:"Org",status:"ACTIVE",createdAt});r.projects.set(ids.p,{id:ids.p,organizationId:ids.o,name:"Project",status:"ACTIVE",createdAt});r.environments.set(ids.e,{id:ids.e,organizationId:ids.o,projectId:ids.p,name:"Prod",kind:"PRODUCTION",status:"ACTIVE",createdAt});const key="iw_live_super_secret_key_material_123456";r.credentials.set(ids.c,{id:ids.c,organizationId:ids.o,projectId:ids.p,environmentId:ids.e,subjectId:ids.s,kind:"API_KEY",keyPrefix:"iw_live",secretHash:hashApiKey(key),scopes:["assets:read","bridge:create"],createdAt});return{r,key,auth:new AuthenticationService(r,undefined,"interweave",()=>new Date("2026-08-13T12:01:00Z"))};}
test("API key authentication returns an immutable active tenant context",async()=>{const v=fixture(),c=await v.auth.authenticateBearer(`Bearer ${v.key}`);assert.equal(c.organizationId,ids.o);assert.equal(c.environmentId,ids.e);assert.equal(c.authenticationMethod,"API_KEY");await assert.rejects(v.auth.authenticateBearer("Bearer iw_live_wrong"),/invalid/);});
test("revoked, expired, suspended, and cross-hierarchy credentials fail closed",async()=>{const v=fixture(),c=v.r.credentials.get(ids.c)!;v.r.credentials.set(ids.c,{...c,revokedAt:"2026-08-13T12:00:00Z"});await assert.rejects(v.auth.authenticateBearer(`Bearer ${v.key}`),/inactive/);const w=fixture();w.r.environments.set(ids.e,{...w.r.environments.get(ids.e)!,projectId:"IW:PROJECT:other"});await assert.rejects(w.auth.authenticateBearer(`Bearer ${w.key}`),/inconsistent/);});
test("OIDC claims require verifier, audience, credential, and exact issuer subject",async()=>{const v=fixture(),current=v.r.credentials.get(ids.c)!;const{secretHash:_secretHash,keyPrefix:_keyPrefix,...base}=current;v.r.credentials.set(ids.c,{...base,kind:"OIDC",subjectId:"https://issuer|user-1"});const auth=new AuthenticationService(v.r,{verify:async()=>({issuer:"https://issuer",subject:"user-1",credentialId:ids.c,audience:"interweave"})},"interweave");assert.equal((await auth.authenticateBearer("Bearer jwt-token")).authenticationMethod,"OIDC");});
test("service authorization scopes operations and idempotency to tenant",async()=>{const context=await fixture().auth.authenticateBearer(`Bearer ${fixture().key}`),calls:any[]=[];const backend=new TenantAuthorizedBackend({execute:async(c,t)=>{calls.push({c,t});return"ok";}},context);await backend.execute({operation:"bridge.create",path:{},query:{},body:{},idempotencyKey:"same-key",requestId:"r"});assert.match(calls[0].c.idempotencyKey,/IW:ORGANIZATION:one.*same-key/);await assert.rejects(backend.execute({operation:"assets.create",path:{},query:{},body:{},idempotencyKey:"x",requestId:"r"}),/missing required scope/);});
test("network grants cannot cross tenant, network, operation, action, or expiry",async()=>{const context=await fixture().auth.authenticateBearer(`Bearer ${fixture().key}`),authorizer=new TenantNetworkAuthorizer(),grant={organizationId:ids.o,projectId:ids.p,environmentId:ids.e,networkId:"IW:NETWORK:evm" as const,operationId:"IW:BRIDGE:one",allowedAction:"MINT",expiresAt:"2026-08-13T13:00:00Z"};assert.doesNotThrow(()=>authorizer.authorize(context,grant,{networkId:grant.networkId,operationId:grant.operationId,action:"MINT"},new Date("2026-08-13T12:00:00Z")));assert.throws(()=>authorizer.authorize(context,grant,{networkId:grant.networkId,operationId:grant.operationId,action:"BURN"}),/not authorized/);});
test("issued API keys expose a prefix but persist only a hash",()=>{const value=issueApiKey();assert.match(value.key,/^iw_live_/);assert.equal(value.secretHash.includes(value.key),false);});
