import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import type { IsoTimestamp, NetworkId } from "./model.js";
import type { RestApiBackend, RestApiCommand, RestOperation } from "./rest-api.js";
import { RegistryError } from "./registry-errors.js";

export type OrganizationId=`IW:ORGANIZATION:${string}`; export type ProjectId=`IW:PROJECT:${string}`; export type EnvironmentId=`IW:ENVIRONMENT:${string}`; export type CredentialId=`IW:CREDENTIAL:${string}`; export type ServiceAccountId=`IW:SERVICE_ACCOUNT:${string}`;
export type Scope="assets:read"|"assets:write"|"identities:write"|"transfers:create"|"bridge:create"|"settlements:create"|"attestations:create"|"transactions:read"|"webhooks:write"|"policies:admin"|"emergency:read"|"emergency:admin";
export interface Organization{id:OrganizationId;name:string;status:"ACTIVE"|"SUSPENDED";createdAt:IsoTimestamp} export interface Project{id:ProjectId;organizationId:OrganizationId;name:string;status:"ACTIVE"|"SUSPENDED";createdAt:IsoTimestamp} export interface TenantEnvironment{id:EnvironmentId;organizationId:OrganizationId;projectId:ProjectId;name:string;kind:"DEVELOPMENT"|"TEST"|"PRODUCTION";status:"ACTIVE"|"SUSPENDED";createdAt:IsoTimestamp}
export interface ServiceAccount{id:ServiceAccountId;organizationId:OrganizationId;projectId:ProjectId;name:string;scopes:readonly Scope[];status:"ACTIVE"|"DISABLED";createdAt:IsoTimestamp}
export interface Credential{id:CredentialId;organizationId:OrganizationId;projectId:ProjectId;environmentId:EnvironmentId;subjectId:ServiceAccountId|string;kind:"API_KEY"|"OIDC";secretHash?:string;keyPrefix?:string;scopes:readonly Scope[];expiresAt?:IsoTimestamp;revokedAt?:IsoTimestamp;createdAt:IsoTimestamp}
export interface TenantContext{organizationId:OrganizationId;projectId:ProjectId;environmentId:EnvironmentId;credentialId:CredentialId;subjectId:string;scopes:readonly Scope[];authenticationMethod:"API_KEY"|"OIDC"}
export interface TenantRegistry{getOrganization(id:OrganizationId):Promise<Organization|undefined>;getProject(id:ProjectId):Promise<Project|undefined>;getEnvironment(id:EnvironmentId):Promise<TenantEnvironment|undefined>;credentialsByPrefix(prefix:string):Promise<readonly Credential[]>;getCredential(id:CredentialId):Promise<Credential|undefined>}
export interface OidcVerifier{verify(token:string):Promise<{issuer:string;subject:string;credentialId:CredentialId;audience:string}|undefined>}

export function hashApiKey(key:string){return `sha256:${createHash("sha256").update(key).digest("hex")}`;} export function issueApiKey(prefix="iw_live"){const secret=randomBytes(32).toString("base64url"),key=`${prefix}_${secret}`;return{key,prefix,secretHash:hashApiKey(key)};}
export class AuthenticationService{
 constructor(readonly registry:TenantRegistry,readonly oidc:OidcVerifier|undefined,readonly expectedAudience:string,readonly now:()=>Date=()=>new Date()){}
 async authenticateBearer(value:string):Promise<TenantContext>{if(!value.startsWith("Bearer "))throw new RegistryError("INVALID_ARGUMENT","Bearer authentication is required");const token=value.slice(7).trim();if(!token)throw new RegistryError("INVALID_ARGUMENT","credential is required");return token.startsWith("iw_")?this.apiKey(token):this.oidcToken(token);}
 async apiKey(key:string){const prefix=key.split("_").slice(0,2).join("_"),hash=hashApiKey(key);for(const credential of await this.registry.credentialsByPrefix(prefix)){if(credential.kind!=="API_KEY"||!credential.secretHash)continue;const a=Buffer.from(hash),b=Buffer.from(credential.secretHash);if(a.length===b.length&&timingSafeEqual(a,b))return this.context(credential,"API_KEY");}throw new RegistryError("NOT_FOUND","credential is invalid");}
 async oidcToken(token:string){if(!this.oidc)throw new RegistryError("NOT_FOUND","OIDC authentication is not configured");const verified=await this.oidc.verify(token);if(!verified||verified.audience!==this.expectedAudience)throw new RegistryError("NOT_FOUND","OIDC token is invalid");const credential=await this.registry.getCredential(verified.credentialId);if(!credential||credential.kind!=="OIDC"||credential.subjectId!==`${verified.issuer}|${verified.subject}`)throw new RegistryError("NOT_FOUND","OIDC subject is not authorized");return this.context(credential,"OIDC");}
 async context(c:Credential,method:TenantContext["authenticationMethod"]){if(c.revokedAt||(c.expiresAt&&this.now().getTime()>=Date.parse(c.expiresAt)))throw new RegistryError("CONFLICT","credential is inactive");const [o,p,e]=await Promise.all([this.registry.getOrganization(c.organizationId),this.registry.getProject(c.projectId),this.registry.getEnvironment(c.environmentId)]);if(!o||!p||!e||o.status!=="ACTIVE"||p.status!=="ACTIVE"||e.status!=="ACTIVE"||p.organizationId!==o.id||e.organizationId!==o.id||e.projectId!==p.id)throw new RegistryError("CONFLICT","tenant hierarchy is inactive or inconsistent");return{organizationId:o.id,projectId:p.id,environmentId:e.id,credentialId:c.id,subjectId:c.subjectId,scopes:[...c.scopes],authenticationMethod:method};}
}
const scopes:Record<RestOperation,Scope>={"networks.list":"assets:read","assets.create":"assets:write","assets.get":"assets:read","assets.balance":"assets:read","identities.create":"identities:write","identities.bind":"identities:write","transfers.create":"transfers:create","transfers.get":"assets:read","bridge.create":"bridge:create","bridge.get":"assets:read","settlements.create":"settlements:create","settlements.get":"assets:read","attestations.create":"attestations:create","attestations.get":"assets:read","transactions.get":"transactions:read","webhooks.create":"webhooks:write","emergency.list":"emergency:read","emergency.create":"emergency:admin","emergency.lift":"emergency:admin"};
export class TenantAuthorizedBackend implements RestApiBackend{constructor(readonly inner:{execute(command:RestApiCommand,tenant:TenantContext):Promise<unknown>},readonly tenant:TenantContext){}async execute(command:RestApiCommand){const required=scopes[command.operation];if(!this.tenant.scopes.includes(required))throw new RegistryError("CONFLICT",`missing required scope: ${required}`);return this.inner.execute({...command,idempotencyKey:command.idempotencyKey?`${this.tenant.organizationId}:${this.tenant.projectId}:${this.tenant.environmentId}:${command.idempotencyKey}`:undefined} as RestApiCommand,this.tenant);}}
export interface NetworkOperationGrant{organizationId:OrganizationId;projectId:ProjectId;environmentId:EnvironmentId;networkId:NetworkId;operationId:string;allowedAction:string;expiresAt:IsoTimestamp}
export class TenantNetworkAuthorizer{authorize(context:TenantContext,grant:NetworkOperationGrant,input:{networkId:NetworkId;operationId:string;action:string},now=new Date()){if(grant.organizationId!==context.organizationId||grant.projectId!==context.projectId||grant.environmentId!==context.environmentId||grant.networkId!==input.networkId||grant.operationId!==input.operationId||grant.allowedAction!==input.action||now.getTime()>=Date.parse(grant.expiresAt))throw new RegistryError("CONFLICT","network operation is not authorized for tenant");}}
export class InMemoryTenantRegistry implements TenantRegistry{organizations=new Map<OrganizationId,Organization>();projects=new Map<ProjectId,Project>();environments=new Map<EnvironmentId,TenantEnvironment>();credentials=new Map<CredentialId,Credential>();async getOrganization(id:OrganizationId){return this.organizations.get(id);}async getProject(id:ProjectId){return this.projects.get(id);}async getEnvironment(id:EnvironmentId){return this.environments.get(id);}async credentialsByPrefix(prefix:string){return[...this.credentials.values()].filter(x=>x.keyPrefix===prefix);}async getCredential(id:CredentialId){return this.credentials.get(id);}}
