import { createHmac, timingSafeEqual } from "node:crypto";
import type { IsoTimestamp } from "./model.js";
import type { SqlExecutor } from "./transaction-engine.js";
import { canonicalJson, requestFingerprint } from "./idempotency.js";
import { RegistryError } from "./registry-errors.js";

export const WEBHOOK_EVENTS = ["transaction.created", "transaction.completed", "transaction.failed", "bridge.source_finalized", "bridge.attested", "bridge.completed", "bridge.failed", "settlement.created", "settlement.completed", "settlement.expired", "reconciliation.failed"] as const;
export type WebhookEventType = typeof WEBHOOK_EVENTS[number];
export interface WebhookEvent { id: `IW:WEBHOOK_EVENT:${string}`; type: WebhookEventType; subjectId: string; data: Readonly<Record<string, unknown>>; occurredAt: IsoTimestamp }
export interface WebhookEndpoint { id: `IW:WEBHOOK:${string}`; url: string; secret: string; events: readonly WebhookEventType[]; enabled: boolean; maxAttempts: number; createdAt: IsoTimestamp }
export interface WebhookDelivery { id: `IW:WEBHOOK_DELIVERY:${string}`; eventId: WebhookEvent["id"]; endpointId: WebhookEndpoint["id"]; attempt: number; status: "PENDING" | "SUCCEEDED" | "RETRY_SCHEDULED" | "DEAD_LETTER"; requestTimestamp: string; signature: string; responseStatus?: number; errorCode?: string; nextAttemptAt?: IsoTimestamp; occurredAt: IsoTimestamp }
export interface WebhookStore { saveEvent(event: WebhookEvent, hash: string): Promise<"CREATED" | "REPLAY">; getEvent(id: WebhookEvent["id"]): Promise<WebhookEvent | undefined>; endpointsFor(type: WebhookEventType): Promise<readonly WebhookEndpoint[]>; saveDelivery(value: WebhookDelivery): Promise<void>; deliveries(eventId: WebhookEvent["id"], endpointId: WebhookEndpoint["id"]): Promise<readonly WebhookDelivery[]> }
export interface WebhookHttpClient { post(input: { url: string; headers: Readonly<Record<string, string>>; body: string }): Promise<{ status: number }> }
export interface WebhookDispatchResult { event: WebhookEvent; deliveries: readonly WebhookDelivery[] }

export class WebhookService {
  constructor(readonly store: WebhookStore, readonly http: WebhookHttpClient, readonly now: () => Date = () => new Date()) {}
  async publish(event: WebhookEvent): Promise<WebhookDispatchResult> {
    validateEvent(event); await this.store.saveEvent(structuredClone(event), requestFingerprint(event)); const deliveries: WebhookDelivery[] = [];
    for (const endpoint of await this.store.endpointsFor(event.type)) { if (!endpoint.enabled) continue; const history = await this.store.deliveries(event.id, endpoint.id); if (history.some((item) => item.status === "SUCCEEDED" || item.status === "DEAD_LETTER")) continue; deliveries.push(await this.attempt(event, endpoint, history.length + 1)); }
    return { event: structuredClone(event), deliveries };
  }
  async retry(eventId: WebhookEvent["id"], endpoint: WebhookEndpoint): Promise<WebhookDelivery> { const event = await this.store.getEvent(eventId); if (!event) throw new RegistryError("NOT_FOUND", `webhook event not found: ${eventId}`); const history = await this.store.deliveries(eventId, endpoint.id); if (history.some((item) => item.status === "SUCCEEDED" || item.status === "DEAD_LETTER")) throw new RegistryError("CONFLICT", "webhook delivery is terminal"); return this.attempt(event, endpoint, history.length + 1); }
  async attempt(event: WebhookEvent, endpoint: WebhookEndpoint, attempt: number): Promise<WebhookDelivery> {
    const body = canonicalJson(event), timestamp = Math.floor(this.now().getTime() / 1000).toString(), signature = signWebhook(endpoint.secret, event.id, timestamp, body); let responseStatus: number | undefined, errorCode: string | undefined;
    try { responseStatus = (await this.http.post({ url: endpoint.url, body, headers: { "content-type": "application/json", "user-agent": "InterWeave-Webhooks/1", "x-interweave-event-id": event.id, "x-interweave-timestamp": timestamp, "x-interweave-signature": signature } })).status; if (responseStatus < 200 || responseStatus >= 300) errorCode = `HTTP_${responseStatus}`; } catch { errorCode = "NETWORK_ERROR"; }
    const success = errorCode === undefined, exhausted = !success && attempt >= endpoint.maxAttempts, occurredAt = this.now().toISOString(); const value: WebhookDelivery = { id: `IW:WEBHOOK_DELIVERY:${event.id}:${endpoint.id}:${attempt}`, eventId: event.id, endpointId: endpoint.id, attempt, status: success ? "SUCCEEDED" : exhausted ? "DEAD_LETTER" : "RETRY_SCHEDULED", requestTimestamp: timestamp, signature, ...(responseStatus !== undefined ? { responseStatus } : {}), ...(errorCode ? { errorCode } : {}), ...(!success && !exhausted ? { nextAttemptAt: new Date(this.now().getTime() + retryDelay(attempt)).toISOString() } : {}), occurredAt };
    await this.store.saveDelivery(value); return structuredClone(value);
  }
}

export function signWebhook(secret: string, eventId: string, timestamp: string, body: string) { if (!secret || !eventId || !/^\d+$/.test(timestamp)) throw new RegistryError("INVALID_ARGUMENT", "webhook signing inputs are invalid"); return `v1=${createHmac("sha256", secret).update(`v1.${eventId}.${timestamp}.${body}`).digest("hex")}`; }
export function verifyWebhook(input: { secret: string; eventId: string; timestamp: string; body: string; signature: string; toleranceSeconds?: number; now?: Date }) { const now = input.now ?? new Date(), tolerance = input.toleranceSeconds ?? 300, seconds = Number(input.timestamp); if (!Number.isSafeInteger(seconds) || Math.abs(Math.floor(now.getTime() / 1000) - seconds) > tolerance) return false; const expected = signWebhook(input.secret, input.eventId, input.timestamp, input.body); const left = Buffer.from(expected), right = Buffer.from(input.signature); return left.length === right.length && timingSafeEqual(left, right); }
function retryDelay(attempt: number) { return Math.min(60 * 60 * 1000, 1000 * 2 ** Math.min(attempt - 1, 12)); }
function validateEvent(value: WebhookEvent) { if (!value.id.startsWith("IW:WEBHOOK_EVENT:") || !WEBHOOK_EVENTS.includes(value.type) || !value.subjectId.trim() || !Number.isFinite(Date.parse(value.occurredAt))) throw new RegistryError("INVALID_ARGUMENT", "webhook event is invalid"); }

export class InMemoryWebhookStore implements WebhookStore {
  readonly events = new Map<string,{event:WebhookEvent;hash:string}>(); readonly endpoints: WebhookEndpoint[] = []; readonly logs: WebhookDelivery[] = [];
  async saveEvent(event: WebhookEvent, hash: string) { const found=this.events.get(event.id); if(found){if(found.hash!==hash) throw new RegistryError("CONFLICT","webhook event ID was reused"); return "REPLAY" as const;} this.events.set(event.id,{event:structuredClone(event),hash}); return "CREATED" as const; }
  async getEvent(id: WebhookEvent["id"]) { const value=this.events.get(id)?.event; return value?structuredClone(value):undefined; } async endpointsFor(type: WebhookEventType){return this.endpoints.filter(x=>x.events.includes(type)).map(x=>structuredClone(x));} async saveDelivery(value:WebhookDelivery){if(this.logs.some(x=>x.id===value.id)) throw new RegistryError("CONFLICT","delivery log is immutable");this.logs.push(structuredClone(value));} async deliveries(eventId:WebhookEvent["id"],endpointId:WebhookEndpoint["id"]){return this.logs.filter(x=>x.eventId===eventId&&x.endpointId===endpointId).map(x=>structuredClone(x));}
}
type Row<T>={record:T}; export class PostgresWebhookStore implements WebhookStore {
  constructor(readonly db:SqlExecutor){} async saveEvent(event:WebhookEvent,hash:string){const result=await this.db.query("INSERT INTO webhook_events (id,event_type,event_hash,record) VALUES ($1,$2,$3,$4::jsonb) ON CONFLICT (id) DO NOTHING",[event.id,event.type,hash,JSON.stringify(event)]);if(result.rowCount===1)return "CREATED";const found=await this.db.query<{event_hash:string}>("SELECT event_hash FROM webhook_events WHERE id=$1",[event.id]);if(found.rows[0]?.event_hash!==hash)throw new RegistryError("CONFLICT","webhook event ID was reused");return "REPLAY";} async getEvent(id:WebhookEvent["id"]){const r=await this.db.query<Row<WebhookEvent>>("SELECT record FROM webhook_events WHERE id=$1",[id]);return r.rows[0]?.record;} async endpointsFor(type:WebhookEventType){const r=await this.db.query<Row<WebhookEndpoint>>("SELECT record FROM webhook_endpoints WHERE enabled=true AND $1=ANY(events)",[type]);return r.rows.map(x=>x.record);} async saveDelivery(v:WebhookDelivery){const r=await this.db.query("INSERT INTO webhook_deliveries (id,event_id,endpoint_id,attempt,status,record) VALUES ($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT (id) DO NOTHING",[v.id,v.eventId,v.endpointId,v.attempt,v.status,JSON.stringify(v)]);if(r.rowCount!==1)throw new RegistryError("CONFLICT","delivery log is immutable");} async deliveries(e:WebhookEvent["id"],p:WebhookEndpoint["id"]){const r=await this.db.query<Row<WebhookDelivery>>("SELECT record FROM webhook_deliveries WHERE event_id=$1 AND endpoint_id=$2 ORDER BY attempt",[e,p]);return r.rows.map(x=>x.record);}
}
