import { InMemoryWorkflowExecutionStore, InMemoryWorkflowRegistry, WorkflowEngine, type GenericStateAttestation, type WorkflowDefinition } from "@interweave/core";
const at="2026-08-13T12:00:00.000Z";
export async function runCollateralCreditExample(){
  const workflow:WorkflowDefinition={id:"IW:WORKFLOW:collateral-credit",version:"1",enabled:true,sourceNetworkId:"IW:NETWORK:ethereum",predicateType:"COLLATERAL_DEPOSIT_FINALIZED",claimEquals:{asset:"TEST_USDC",minimumAmount:"100000000"},policyId:"IW:POLICY:credit",policyVersion:"1",actionType:"RECORD_CANTON_COLLATERAL",actionConfiguration:{facility:"DEMO_CREDIT_LINE"},createdAt:at};
  const attestation:GenericStateAttestation={statement:{version:"1",id:"IW:ATTESTATION:collateral-deposit",idempotencyKey:"collateral-deposit-1",sourceNetworkId:"IW:NETWORK:ethereum",sourceNetworkType:"EVM",sourceTransactionId:"0xdeposit",sourceEventPosition:"block:100/log:2",predicateType:"COLLATERAL_DEPOSIT_FINALIZED",claims:{asset:"TEST_USDC",minimumAmount:"100000000",depositor:"0xAlice"},nonce:"example_nonce_00000001",policyVersion:"1",validatorSetId:"validators-1",threshold:2,validFrom:at,expiresAt:"2026-08-13T13:00:00.000Z",createdAt:at,observedStatePosition:"finalized:110",observedAt:at},signatures:[],validatorEvidence:{},digest:"sha256:example",status:"VERIFIED_EVIDENCE_ONLY",destinationMutationAuthorized:false,recordedAt:at};
  const registry=new InMemoryWorkflowRegistry();await registry.register(workflow);let activations=0;const engine=new WorkflowEngine(registry,{verify:async()=>true},{authorize:async()=>({outcome:"ALLOW",policyId:workflow.policyId,policyVersion:workflow.policyVersion,reasons:["COLLATERAL_POLICY_MET"]})},[{actionType:"RECORD_CANTON_COLLATERAL",execute:async()=>{activations++;return{outcome:"APPLIED",evidence:{externalTransactionId:"canton:credit-line:1",observedPosition:"offset:200",evidence:["collateral-recorded"],finalizedAt:at}}}}],new InMemoryWorkflowExecutionStore(),()=>new Date(at));
  const result=await engine.execute({id:"IW:WORKFLOW_EXECUTION:collateral-credit-1",idempotencyKey:"collateral-credit-1",workflowId:workflow.id,workflowVersion:workflow.version,attestation,createdAt:at});
  return{example:"Ethereum collateral to Canton credit-line activation",status:result.status,activations,evidenceOnly:attestation.destinationMutationAuthorized===false,authorizedBy:`${workflow.id}@${workflow.version}`};
}
