import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { ContractFactory, JsonRpcProvider, Wallet, id } from "ethers";
import { compileContracts } from "../compile-contracts.mjs";
import { assertNonProductionChain, loadTarget, redactUrl, requireConfirmation } from "./deployment-policy.mjs";

const root=path.resolve(import.meta.dirname,"../.."),target=await loadTarget(path.join(root,"config/testnet/sepolia.json"));requireConfirmation(target,process.env.INTERWEAVE_TESTNET_CONFIRM);
if(!process.env.SEPOLIA_RPC_URL||!process.env.TESTNET_DEPLOYER_PRIVATE_KEY)throw new Error("SEPOLIA_RPC_URL and TESTNET_DEPLOYER_PRIVATE_KEY are required");
const provider=new JsonRpcProvider(process.env.SEPOLIA_RPC_URL),network=await provider.getNetwork();assertNonProductionChain(network.chainId);if(network.chainId!==BigInt(target.chainId))throw new Error("RPC chain does not match Sepolia target");
const signer=new Wallet(process.env.TESTNET_DEPLOYER_PRIVATE_KEY,provider),balance=await provider.getBalance(signer.address);if(balance===0n)throw new Error("testnet deployer has no Sepolia ETH");const compiled=compileContracts();
async function deploy(file,name,args=[]){const a=compiled[file]?.[name];if(!a)throw new Error(`missing artifact ${file}:${name}`);const c=await new ContractFactory(a.abi,`0x${a.evm.bytecode.object}`,signer).deploy(...args);await c.waitForDeployment();return c;}
const admin=signer.address,verifier=await deploy("contracts/ethereum/AttestationVerifier.sol","AttestationVerifier",[admin,admin,[admin],1]),registry=await deploy("contracts/ethereum/InterWeaveAssetRegistry.sol","InterWeaveAssetRegistry",[admin,admin]),gateway=await deploy("contracts/ethereum/InterWeaveGateway.sol","InterWeaveGateway",[admin,admin,await verifier.getAddress(),await registry.getAddress()]),representation=await deploy("contracts/ethereum/InterWeaveRepresentation.sol","InterWeaveRepresentation",["InterWeave Sepolia RWA","iwSepRWA",18,admin,await gateway.getAddress()]),assetId=id("INTERWEAVE_SEPOLIA_RWA_V1");await(await registry.configure(assetId,await representation.getAddress(),"0x0000000000000000000000000000000000000000",true)).wait();
const block=await provider.getBlockNumber(),manifest={version:1,target:target.name,chainId:network.chainId.toString(),rpc:redactUrl(process.env.SEPOLIA_RPC_URL),deployer:signer.address,deployedAt:new Date().toISOString(),deploymentBlock:block,assetId,contracts:{verifier:await verifier.getAddress(),registry:await registry.getAddress(),gateway:await gateway.getAddress(),representation:await representation.getAddress()},productionPromotion:"PROHIBITED"};const out=path.join(root,"deployments/testnet/sepolia.json");await mkdir(path.dirname(out),{recursive:true});await writeFile(out,`${JSON.stringify(manifest,null,2)}\n`,{flag:"wx"});console.log(`Sepolia deployment recorded at ${out}`);
